### ISSUE TITLE
How do I install this and use it?

### ISSUE THREAD

**Issue by x11joe** [atom/decoration-example#4]
I'm new to atom and not sure where I go to install this?

**Comment by rsese** [comment]
Looks like this example package was never published so you can't install it from Settings View or through apm:

https://discuss.atom.io/t/what-happened-to-the-decoration-example-package/12241/3

You can use it with this process described in the Flight Manual:

http://flight-manual.atom.io/hacking-atom/sections/contributing-to-official-atom-packages/#hacking-on-packages

```
git clone https://github.com/atom/decoration-example
cd decoration-example
apm install
apm link -d
atom --dev
```
